Shindo.tests do
  returns(true, 'exception') { raise StandardError.new('exception') }
end